spring.profiles.active: development
---
spring:
  profiles: cloud
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.1.128}
    port: ${SPRING_NEO4J_PORT:7474}
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/dev2?useSSL=false
    username: root
    password: dbpass
    initialize: true
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.128:8761/eureka/
---
spring:
  profiles: docker
  neo4j:
    host: ${SPRING_NEO4J_HOST:neo4j}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  neo4j:
    host: ${SPRING_NEO4J_HOST:192.168.1.128}
    port: ${SPRING_NEO4J_PORT:7474}
eureka:
  client:
    enabled: false
